# sudo docker-compose build
# sudo docker-compose up
# sudo docker-compose up --build

# Subir em background
# sudo docker-compose -f docker-compose.yml up -d

# How use iterative mode container
# sudo docker-compose exec debian10_php8 bash


#Purging All Unused or Dangling Images, Containers, Volumes, and Networks
#sudo docker system prune -a

version: '3.8'
services:

  apache_php:
    build:
      dockerfile: adianti_debian11_php8.1.Dockerfile
      context: .
    image: adianti_debian11_php8.1:last
    container_name: adianti_debian11_php8.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - formdin-network
    volumes:
      - ./php.ini:/etc/php/8.1/apache2/php.ini
      - ./www:/var/www/html:rw
      - ./logs:/var/log/apache2:rw
      #- ./config/apache_default.conf:/etc/apache2/sites-enabled/000-default.conf

networks: 
    formdin-network:
        driver: bridge