# sudo docker-compose build
# sudo docker-compose up

# Subir em background
# sudo docker-compose -f docker-compose.yml up -d

# How use iterative mode container
# sudo docker-compose exec apache_php bash
version: '3.2'
services:

  database:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: form
      MYSQL_USER: form
      MYSQL_PASSWORD: form
    ports:
      - "3306:3306"      
    networks: 
      - formdin-network
    #volumes:
    # - ./data/db:/var/lib/mysql
    # - ./database/mysql:/var/lib/mysql

  apache_php:
    build:
      dockerfile: apache_php7.2.Dockerfile
      context: .
    image: devform:7.2-deb-apache
    container_name: apache_php
    restart: always    
    ports:
      - "80:80"
    networks:
      - formdin-network
    volumes:
      - ./www:/var/www/html
    depends_on:
      - database

networks: 
    formdin-network:
        driver: bridge