# sudo docker-compose build
# sudo docker-compose up

# Subir em background
# sudo docker-compose -f docker-compose.yml up -d

# How use iterative mode container
# sudo docker-compose exec ubuntu_apache_php bash


#Purging All Unused or Dangling Images, Containers, Volumes, and Networks
#sudo docker system prune -a

version: '3.2'
services:

  apache_php:
    build:
      dockerfile: debian10_apache_php8.Dockerfile
      context: .
    image: debian10_apache_php8:last
    container_name: debian10_php8
    restart: always
    ports:
      - "80:80"
    networks:
      - formdin-network
    volumes:
      #- "d:/wamp/www/formDocker:/var/www/html"  #windows    
      - ./www:/var/www/html                    #Linux


networks: 
    formdin-network:
        driver: bridge
