# sudo docker-compose build
# sudo docker-compose up
# sudo docker-compose up --build

# Subir em background
# sudo docker-compose -f docker-compose.yml up -d

# How use iterative mode container
# sudo docker-compose exec debian10_php8 bash


#Purging All Unused or Dangling Images, Containers, Volumes, and Networks
#sudo docker system prune -a

version: '3.6'
services:

  apache_php:
    build:
      dockerfile: adianti_debian10_apache_ph7.4.Dockerfile
      context: .
    image: adianti_debian10_apache_ph7.4:last
    container_name: debian10_php8
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - formdin-network
    volumes:
      #- "d:/wamp/www/formDocker:/var/www/html" #Windows 7
      - ./www:/var/www/html:rw                     #Linux
      - ./logs:/var/log/apache2:rw
      #- ./config/:/etc/php
      #- ./config/apache_default.conf:/etc/apache2/sites-enabled/000-default.conf

networks: 
    formdin-network:
        driver: bridge
