# sudo docker-compose build
# sudo docker-compose up

# Subir em background
# sudo docker-compose -f ubuntu_apache_php70_pdo_db.yml up -d

# How use iterative mode container
# sudo docker-compose exec ubuntu_apache_php bash


#Purging All Unused or Dangling Images, Containers, Volumes, and Networks
#sudo docker system prune -a

version: '3.2'
services:

  apache_php:
    build:
      dockerfile: ubuntu_apache_php70.Dockerfile
      context: .
    image: ubuntu_apache_php70:latest
    container_name: ubuntu_php70
    restart: always    
    ports:
      - "80:80"
    networks:
      - formdin-network
    volumes:
      #- "d:/wamp/www/formDocker:/var/www/html"  #windows    
      - ./www:/var/www/html                    #Linux


networks: 
    formdin-network:
        driver: bridge
