<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * ALTERADO PARA EXEMPLO DOCKER
 */

define('BANCO'   , 'MYSQL');
define('HOST'    , 'mysql');
define('PORT'    , '3306');
define('DATABASE', 'form_exemplo');
define('SCHEMA'  , '');
define('USUARIO' , 'form_exemplo');
define('SENHA'   , '123456');
define('UTF8_DECODE'   , 0);
?>
