# sudo docker-compose build
# sudo docker-compose up
# sudo docker-compose up --build

# Subir em background
# sudo docker-compose -f docker-compose.yml up -d

# How use iterative mode container
# sudo docker-compose exec debian10_php8 bash


#Purging All Unused or Dangling Images, Containers, Volumes, and Networks
#sudo docker system prune -a

version: '3.2'
services:


  #database:
    #image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
    #container_name: sqlserver
    #restart: always
    #environment:
    #  ACCEPT_EULA: Y
    #  SA_PASSWORD: 123456
    #  MSSQL_PID: Developer
    #ports:
    #  - "1433:1433"
    #networks: 
    #  - formdin-network
    #volumes:
    # - ./data/db:/var/lib/mysql
    # - ./database/mysql:/var/lib/mysq

  apache_php:
    build:
      dockerfile: debian10_apache_php74_mssql.Dockerfile
      context: .
    image: debian10_apache_php74_mssql:last
    container_name: debian10_apache_php74_mssql
    restart: always
    ports:
      - "80:80"
    networks:
      - formdin-network
    volumes:
      - ./www:/var/www/html:rw                  #Linux
      - ./logs:/var/log/apache2:rw
      #- ./config/:/etc/php
      #- ./config/apache_default.conf:/etc/apache2/sites-enabled/000-default.confif
    #depends_on:
    #  - database

networks: 
    formdin-network:
        driver: bridge
